name = "kimpure/project_fast_setup"
version = "0.1.0"
description = "can fast setup project (for luau, lune)"
authors = ["kimpure"]
repository = "https://github.com/kimpure/luau-project-fast-setup"
license = "MIT"
includes = ["README.md", "LICENSE.md", "bin.luau", "pesde.toml"]

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.2.1" }